### ISSUE TITLE
Make sure SimpleIdentifier role is applied consistently with Python

### ISSUE THREAD

**Issue by bzz** [bblfsh/java-driver#22]
Based on discussion on [#babaelfish channel](https://sourced-community.slack.com/archives/C5JAKNM99/p1497507342068218), we need to have analog of bblfsh/python-driver#23

**Comment by abeaumont** [comment]
@bzz SimpleIdentifier role annotation seems to be working ok, do you have any sample code working improperly?

**Comment by bzz** [comment]
Thanks reminding! Let me double check and get back to this later this sprint.

**Comment by bzz** [comment]
On quick glance, comparing roles in https://github.com/bblfsh/python-driver/pull/23/files with UAST for [Notification.java](https://github.com/damoeb/kalipo/blob/master/kalipo-service/src/main/java/org/kalipo/domain/Notification.java) and [telepolis_spider.py](https://github.com/damoeb/kalipo/blob/master/kalipo-ir/harvester/spiders/telepolis_spider.py)

 1. ❓ TypeDeclaration
  in Python `TypeDeclaration, SimpleIdentifier`
  In Java

    ```
    7: TypeDeclaration {
    .  .  .  Roles: VisibleFromWorld,TypeDeclaration
    ```

 2. ✅ FunctionDeclarations
  `FunctionDeclarationName` in Java and `FunctionDeclaration` (\wo Name) in Python both are `SimpleIdentifier`

 3. ❓ AssignmentValue
   In java `Roles: SimpleIdentifier,AssignmentValue` in Python `AssignmentValue` seems not have `SimpleIdentifier`
  
I might be reading it wrong, but it looks like some further investigation might be required.

**Comment by abeaumont** [comment]
@bzz roles are associated with nodes in built from the native parser, not with other roles. I mean by that that relations between nodes in different languages is `m` to `n`, not `1` to `1`, that is, one node in Python may match to a set of nodes in Java and viceversa. In that case, different `roles` may be spread between different nodes. And I think this is happening in the first 2 cases:

1. In this case, in Java, the `SimpleIdentifier` role is not in the `TypeDeclaration` node, but in one of its children.
2. In this case, I don't think a `FunctionDeclaration` should be a `SimpleIdentifier`, which is correct in the case of the Java sample. In the case of the Python sample, the AST has a single node for both `FunctionDeclaration` and `FunctionDeclarationName`, and thus it makes sense to be also a `SimpleIdentifier`.
3. `AssignmentValue` may or may not be a `SimpleIdentifier`, depending on whether it's effectively an identifier. In the python sample the assigment values are really values (literals), while in the java sample they're identifiers (since there're setters).

**Comment by bzz** [comment]
👍  sounds good. I just was under impression that on the Role level, they might be expected to co-occur. 

This issue was only about making sure cases like assignment and function\class declarations have SimpleIdentifies in both languages. 

I guess more detailed verification could be done as soon as we have nice UI UAST explorer.

**Comment by abeaumont** [comment]
Ok, I'll close this for now, and we can handle more detailed issues as they appear.
