### ISSUE TITLE
improve error reporting

### ISSUE THREAD

**Issue by smola** [bblfsh/java-driver#7]
Whenever there is an error in the code, the driver should:

* add an error in the response.
* when the AST is generated, some error mark would need to be included in a node when children are omitted because of errors

**Comment by bzz** [comment]
This would be really nice, from my experience python drive is already doing it and it would help i.e #23

It would be also super-cool to propagate this information to clients, rather then failing them with `panic`

**Comment by abeaumont** [comment]
@smola In case of parsing errors I'd just return the `error` status. I'm not sure the ast of an erroneously parsed code should be of any use. If you think it'd be, then I'd use an optional property `error` with a boolean value (`true` or `false`). It could work in one of two ways:

* It only appears in nodes with parsing errors.
* It appear in every node when there's some kind of parsing error.

In both cases the `status` would be `error`. I wouldn't include the property if there's no error. I'm not sure which option would be best since I have no use case in mind of when an erroneous `ast` could be useful.

**Comment by smola** [comment]
@abeaumont I think erroneous `ast` would be mostly non-useful for us, except maybe in the case of comparing AST for different revisions. Think of something like `this commit change this variable name, and it replaced this subtree with something broken`. Not something we're planning to do any time soon anyway. And it's kind of tricky, because a lot of parsers will produce no AST at all if it has an error, so this is not something we can apply everywhere.

I think that at this point, the really imporant part is having the right `Status`. And if `Status` is error, it is also _nice to have_ at least one error message in `Errors` with something useful for the user, if available in the parser (e.g. `parsing error: shit happened at line 5`).

**Comment by abeaumont** [comment]
Nice, since handling `status` and `errors` doesn't require to traverse the `ast` to check and mark nodes as erroneous, so I'll stick to that for now, we can go further in the future if needed
