### ISSUE TITLE
Response have an error status but UAST also

### ISSUE THREAD

**Issue by zurk** [bblfsh/java-driver#77]
I am not sure if it correct behavior or not, but for this file:
[4132.txt](https://github.com/bblfsh/java-driver/files/1995537/4132.txt) (it is java code)
and python code to run:
```python
import bblfsh
bf = bblfsh.BblfshClient("0.0.0.0:9432")
print(bf.parse(taskpath, language="Java"))
```
I have:
```
status: ERROR
errors: "Syntax error on tokens, delete these tokens"
elapsed {
  nanos: 40917102
}
uast {
  internal_type: "CompilationUnit"
  children {

...

  roles: FILE
}
language: "java"
```

there is full UAST inside. 

so is UAST not valid or is it wrong status inside the response?

**Comment by zurk** [comment]
update: it is not correct Java code.

**Comment by dennwc** [comment]
The response looks valid to me. There are 3 statuses: `OK`, `Error` and `Fatal`. `Error` means that driver was able to process a part of the file, but there might be some syntax errors, thus the AST, in this case, might be incomplete. `Fatal` on the other hand would mean that driver fail completely.

For user applications, I would suggest accepting AST only for `OK` status codes because right now there is no guarantee on how complete an AST would be on `Error` (it might be empty for some drivers).

**Comment by bzz** [comment]
> For user applications, I would suggest accepting AST only for OK status codes because right now there is no guarantee on how complete an AST would be on Error (it might be empty for some drivers).

@dennwc do you think it could be helpful then to document this suggestion somewhere in the official docs of the bblfsh project? 

I find error reporting not very straightforward at all, and we already might have number of users of bblfsh clients, treat this situation in a [different fashion](https://github.com/src-d/gemini/blob/master/src/main/scala/tech/sourced/gemini/FileQuery.scala#L115).

**Comment by dennwc** [comment]
@bzz @zurk I'm closing this in favor of https://github.com/bblfsh/sdk/issues/257, since it's not Java-related.
